global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'api-gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:5000']

  - job_name: 'blog-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['blog-service:5001']

  - job_name: 'user-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['user-service:5002']

  - job_name: 'comment-service'
    metrics_path: /metrics
    static_configs:
      - targets: ['comment-service:5003']

  - job_name: 'blackbox'
    metrics_path: /metrics
    static_configs:
      - targets: ['blackbox-exporter:9115']

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api-gateway:5000/health
        - http://blog-service:5001/health
        - http://user-service:5002/health
        - http://comment-service:5003/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-metrics'
    metrics_path: /probe
    params:
      module: [http_metrics]
    static_configs:
      - targets:
        - http://api-gateway:5000/metrics
        - http://blog-service:5001/metrics
        - http://user-service:5002/metrics
        - http://comment-service:5003/metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017'] 